export const COURSE_UNITS = [
  "SENAC DF",
  "Asa Norte",
  "Taguatinga",
  "Gama",
  "Ceilândia",
  "Sobradinho",
  "Jessé Freire",
  "Santa Maria",
  "São Sebastião",
  "Brazlândia",
  "Joaquim Loiola",
  "Jo Rufino e Carlos Aguiar",
  "Miguel Setembrino",
  "Miguel Setembrino - Gastronomia",
  "Miguel Setembrino - Saúde",
  "Talal Abu-Allan",
] as const;

export const COURSE_SEGMENTS = [
  "Gastronomia",
  "Ambiente e Saúde",
  "Gestão e Moda",
  "Tecnologia e Econ. Criativa",
  "Tecnologia e Economia Criativa",
  "Beleza e Cuidado Pessoal",
  "60+",
  "Ensino Médio",
  "Bebidas",
  "Panificação",
  "Confeitaria",
  "Turismo",
  "Hospitalidade",
  "Design",
  "Design, Paisagismo e Ambientação",
  "Paisagismo e Jardinagem",
  "Produção Cultural e Design",
  "Comunicação",
  "Comunicação e Audiovisual",
  "Artes",
  "Eventos",
  "Tecnologia da Informação - Suporte",
  "Tecnologia da Informação - Games",
  "Tecnologia da Informação - Inovação",
  "Tecnologia da Informação - Desenvolvimento",
  "Tecnologia e Games",
  "TI",
  "Gestão",
  "Gestão e Comércio",
  "Gestão e Negócios",
  "Comércio",
  "Educação",
  "Vendas e Marketing",
  "Moda e Costura",
  "Estética e Massoterapia",
  "Enfermagem",
  "Radiologia",
  "Saúde Bucal",
  "Nutrição",
  "Análises Clínicas",
  "Farmácia",
  "Segurança e NRs",
  "Administrativo / Serviços em Saúde",
] as const;

export const COURSE_STATUSES = [
  "ATIVO",
  "INATIVO",
  "PUBLICADO",
  "PUBLICADO NO INTRANET/INDISPONÍVEL NO SITE",
  "PUBLICADO NO INTRANET/INDISPONÍVEL NO SITE E SIG",
  "EM ANÁLISE",
  "EM PROCESSO DE ELABORAÇÃO",
  "EM PROCESSO DE APROVAÇÃO",
  "AGUARDANDO",
  "CPED",
  "CPFD",
  "ARQUIVADO",
  "CANCELADO",
  "SUSPENSO",
  "REVOGADO",
] as const;

/**
 * Modalidade educacional do curso (coluna "Modalidade" da planilha de portfólio).
 * Inclui formato de oferta (Presencial/EAD/Híbrido) e linhas de produto SENAC (FIC, Habilitação etc.).
 */
export const COURSE_MODALITIES = [
  "Presencial",
  "EAD",
  "Híbrido",
  "FIC",
  "Habilitação Técnica",
  "Técnico de Nível Médio",
  "Ação Extensiva",
  "Especialização",
  "Programa",
] as const;

/**
 * Tipo de curso (coluna "TIPO" da planilha de portfólio).
 * Valores legados em CAIXA ALTA são normalizados via courseFieldNormalization.
 */
export const COURSE_TYPES = [
  "Aperfeiçoamento",
  "Aperfeiçoamento/Atualização",
  "Qualificação Profissional",
  "Habilitação Técnica",
  "Programa Socioprofissional",
  "Programa Instrumental",
  "Aprendizagem Profissional",
  "Iniciação Profissional",
  "Especialização Técnica",
  "Especialização",
  "Oficina",
] as const;
